FROM --platform=linux/amd64 ubuntu:20.04

RUN apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get install -y build-essential wget zlib1g-dev unzip
ADD . /repo
WORKDIR /repo/source
RUN make -j8 STARstatic
RUN mkdir test
